### ISSUE TITLE
Better responsive img

### ISSUE THREAD

**Issue by MarcelHekkert** [leejordan/reflex#17]
I have just started using reflex. When using a responsive image with just grid__cell-img it always scales up (probably also when used inside a cell!). It can be more flexible to make the upscale an extra class. The classname I have used is just a suggestion.

.@{reflex-prefix}grid__cell-img {
        display: block;
        .display-flex-only();
        .flex(0, 0, auto);
        margin-left: 0;
        margin-right: 0;
        max-width: 100%;
        height: auto;

```
    &.img-full-width{
        width: 100%;
    }
}
```

**Comment by leejordan** [comment]
My thinking on this is if you want the image treated as a flex item, you use the `grid__cell-img` class so it fills the available space correctly, otherwise you set up a `grid__cell` within which you can treat images however you like as they are then out of the flexbox flow.

However maybe this isn't clear, or ideal. I'm open to further discussion and suggestions.
