### ISSUE TITLE
Bug in IE11 with IE9 emulation mode on Windows 10

### ISSUE THREAD

**Issue by Mr-Robby** [leejordan/reflex#23]
Hello! I found bug on IE11 (11.420v)  with IE9 emulation mode. `display: inline-block` override by `display:flex`. Here's [screenshot](https://cloud.githubusercontent.com/assets/3427043/16333751/ab1db29e-3a05-11e6-9836-3543c70b3695.png)

**Comment by leejordan** [comment]
Thanks for your bug report.

I double checked this in browserstack and on a virtual machine running ie9 and the bug does not happen there. It appears to only occur in ie9 emulation mode in ie11 as you say. 

I'm not sure there is much I can do to address this bug except maybe update the documentation to mention it and recommend using a VM or browserstack for ie9 testing instead of ie9 emulation.

**Comment by Mr-Robby** [comment]
Ok, thank you for help!
