### ISSUE TITLE
Question:  Dropped !important in v2 intentional?

### ISSUE THREAD

**Issue by miketdonahue** [leejordan/reflex#47]
Hey @leejordan,

I have noticed in v2 that all of the "!important" was dropped from the auto cols, the .grid class, and the .hidden helpers.  I just want to confirm that this was intentional and that we aren't missing anything in v2?

https://github.com/leejordan/reflex/blob/master/scss/includes/_mixins.scss#L43-L49

Thanks!

**Comment by leejordan** [comment]
Those !importants were previously used to get around CSS specificity problems. With the rewrite I was able to plan it all out so these were no longer required.

You should find the examples work even without them because of the new way it is all structured.

http://reflexgrid.com/docs/#auto-grid
http://reflexgrid.com/docs/#visibility-helpers

**Comment by miketdonahue** [comment]
Cool, thanks!
